0.1.9

diff --git a/6/bin/sparky-play b/6/bin/sparky-play
--- a/6/bin/sparky-play
+++ b/6/bin/sparky-play
@@ -4,7 +4,7 @@
 ##---------------------------------------------------------------------------
 ## Sparky Play
 ## Sob a licença GNU GPL v3
-# Last update 2020/10/11 by pavroo
+# Last update 2020/10/24 by pavroo
 
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-play"
@@ -28,20 +28,26 @@ fi
 
 YAD="yad --center --window-icon=mpv --width=500 --height=100 --title="
 ENTRY="--entry"
-RICON="--ricon=gtk-clear --ricon-action=echo "
-BUTCAN="--button=gtk-cancel:1"
-BUTSEA="--button=gtk-find:0"
-BUTCLOSE="--button=gtk-close:1"
-BUTSTOP="--button=gtk-media-stop:0"
+#RICON="--ricon=gtk-clear --ricon-action=echo "
+BUTCAN="--button=Cancel!gtk-cancel!tooltip:1"
+BUTSEA="--button=Find!gtk-find!tooltip:0"
+BUTCLOSE="--button=Close!gtk-close!tooltip:1"
+BUTSTOP="--button=Stop!gtk-media-stop!tooltip:0"
 TITLE="Sparky Play MP3"
 FORM="--form"
-COLUMNS="--columns="
+#COLUMNS="--columns"
 FIELD="--field="
 IMAGE="--image-on-top --image=mpv --text="
 FOCUS="--focus-field="
 
+CHECKFFPLAY=`which ffplay`
+if [ "$CHECKFFPLAY" = "" ]; then
+	$YAD"$TITLE" $IMAGE"\nffplay is missing, install it:\n\nsudo apt install ffplay" $BUTCLOSE
+	exit 1
+fi
+
 ## functions
-## function error 
+# function error 
 function _void(){
 		rm -rf /tmp/tmp.txt
 		rm -rf /tmp/list_music.list
@@ -53,11 +59,11 @@ function _void(){
 function _search() {
 	if FORM_SEARCH=$($YAD"$TITLE" $IMAGE"$LOCAL2" \
 					$FORM $FOCUS"1" \
-					$FIELD:LBL $FIELD:LBL \
-					$FIELD$LOCAL9 \
-					$FIELD:LBL $FIELD:LBL \
-					$FIELD$LOCAL10:DIR \
-					$FIELD:LBL $FIELD:LBL \
+					$FIELD!tooltip:LBL $FIELD!tooltip:LBL \
+					$FIELD$LOCAL9!tooltip \
+					$FIELD!tooltip:LBL $FIELD!tooltip:LBL \
+					$FIELD$LOCAL10!tooltip:DIR \
+					$FIELD!tooltip:LBL $FIELD!tooltip:LBL \
 					$BUTCAN $BUTSEA)
 	then
 		FORM_TXT=$(echo $FORM_SEARCH | cut -d "|" -f3)
@@ -93,21 +99,21 @@ function _play() {
 	else
 	    EXTERN="$*"
 		MUSICS=$(cat "$LIST" | grep "$1" | cut -d : -f1)
-		[ -z "$MUSICS"] && ffplay -nodisp -loop 0 "$EXTERN" || ffplay -nodisp -loop 0 "$MUSICS"
+		[ -z "$MUSICS" ] && ffplay -nodisp -loop 0 "$EXTERN" || ffplay -nodisp -loop 0 "$MUSICS"
 	fi	 
 }
 
-## function selected music
+# function selected music
 function _main() {
 	if [ ! -f "$LIST" ]; then
 		export LIST="/tmp/list_music.list"
 		_search
 	fi
 	COMBO=$(cat "$LIST" | cut -d ':' -f2 | sort | tr '\n' '!')
-	if $YAD"$TITLE" $IMAGE"$LOCAL5" $FORM $COLUMNS"3" \
-		$FIELD$LOCAL6:CB "$COMBO" \
-		$FIELD$LOCAL8:BTN "/usr/bin/sparky-play play %1" \
-		$FIELD'gtk-media-stop':BTN "killall -9 ffplay" \
+	if $YAD"$TITLE" $IMAGE"$LOCAL5" $FORM --columns=3 \
+		$FIELD"$LOCAL6!tooltip":CB "$COMBO" \
+		$FIELD"$LOCAL8!tooltip":BTN "/usr/bin/sparky-play play %1" \
+		$FIELD"Stop!gtk-media-stop!tooltip":BTN "killall -9 ffplay" \
 		$BUTCLOSE $BUTSEA
 	then
 		killall -9 ffplay
@@ -124,4 +130,3 @@ case "$1" in
 	'play') shift; _play "$*" ;;
 	*) _main ;;
 esac
-
